#!/usr/bin/perl
#password guesser
use strict; use warnings;

my $password = "beben";
my @alphabet = ('a' .. 'z');

for (my $i = 1; $i <= 10**10; $i++) {
	my $first = $alphabet[rand(26)];
	my $second = $alphabet[rand(26)];
	my $third = $alphabet[rand(26)];
	my $fourth = $alphabet[rand(26)];
	my $fifth = $alphabet[rand(26)];
	my $guess = $first . $second . $third . $fourth . $fifth;
	if ($guess eq $password) {
		print "Attempt $i: the password is $guess!\n";
		last;
	}
}
